In [11]:
import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\patha\Downloads\messy_customer_sales_data.csv")
df.head()

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
0,CUST4371,Paul Wilson,m,52.0,KOLKATA,2025-06-26,2025-05-17,26944.0,1.0,peckvictoria@example.com,2131107701,India
1,CUST5957,Jason Thomas,M,51.0 years,NaN,2021-02-17,2025-07-22,44152.0,2.0,owensanthony@example.com,1080761560,india
2,CUST3754,Brittney Martinez,F,62.0,hyderabad,2023-11-05,2024-12-08,31745.0,2.0,tara39@example.org,8981006345,India
3,CUST2934,Brenda Pierce,FEMALE,40.0,hyderabad,2022-03-13,2025-10-02,39674.0,1.0,berrynancy@example.org,8228064204,india
4,CUST5683,Matthew Carroll,f,41.0,CHENNAI,2024-04-05,2024-12-15,NaN,8.0,denise84@example.org,2665569480,India

In [14]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10200 entries, 0 to 10199
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Customer_ID         9177 non-null   str
 1   Name                10200 non-null  str
 2   Gender              9174 non-null   str
 3   Age                 9249 non-null   str
 4   City                9184 non-null   str
 5   Signup_Date         10200 non-null  str
 6   Last_Purchase_Date  9188 non-null   str
 7   Purchase_Amount     9179 non-null   float64
 8   Feedback_Score      9177 non-null   float64
 9   Email               10200 non-null  str
 10  Phone_Number        10200 non-null  int64
 11  Country             9468 non-null   str
dtypes: float64(2), int64(1), str(9)
memory usage: 956.4 KB

In [16]:
df.describe().round()

       Purchase_Amount  Feedback_Score  Phone_Number
count           9179.0          9177.0  1.020000e+04
mean           29090.0             5.0  4.979974e+09
std           208697.0             3.0  2.902593e+09
min             -500.0             1.0  9.208990e+05
25%            12295.0             3.0  2.449157e+09
50%            24330.0             5.0  4.988639e+09
75%            37130.0             8.0  7.510448e+09
max          9999999.0            10.0  9.994402e+09

In [23]:
df[df.duplicated()]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
3191,NaN,Travis Schneider,f,51.0,NaN,2025-04-20,2025-02-28,48750.0,5.0,bianca77@example.net,7623118785,India
4312,CUST8305,Stanley Cain,FEMALE,51.0,Bangalore,2023-08-14,2024-11-01,11432.0,6.0,calderonbrenda@example.org,4889366037,India
5611,CUST6288,Jonathon Kim,male,46.0,Chennai,2023-11-22,2025-03-21,3301.0,6.0,tparker@example.com,5266662560,India
5680,CUST2695,Lisa Durham,NaN,46.0,Chennai,2021-04-18,2024-10-10,6511.0,3.0,andrew34@example.com,2235480149,India
5899,CUST8841,Amanda Hill,NaN,34.0,chennai,2022-09-11,2025-03-13,42092.0,4.0,ryanriley@example.net,3466026146,India
6070,CUST10780,Emily Smith,NaN,23.0,Kolkata,2023-12-09,2024-10-28,18027.0,5.0,perezchristopher@example.com,3032282870,India
6240,CUST9745,David Morales,NaN,56.0,NaN,2023-02-18,2024-12-14,49107.0,7.0,juliaknapp@example.com,9436163110,India
6425,CUST4631,George Villa,m,26.0,Mumbai,2022-05-21,2025-06-17,NaN,8.0,davidmarquez@example.com,8869465862,India
6498,CUST1711,Stephanie Elliott,NaN,44.0,MUMBAI,2023-05-17,2025-07-12,11349.0,9.0,nfischer@example.com,3270872546,NaN
7118,CUST9380,Paul Wilson,MALE,42.0,Bangalore,2025-07-31,2025-09-21,2696.0,5.0,steven57@example.net,6835989909,India
8392,CUST1436,Ralph Anderson,female,33.0,Kolkata,2022-10-21,2025-04-24,42870.0,NaN,vcosta@example.com,3739220307,India
9155,CUST10040,Mark Taylor,NaN,43.0,Delhi,2021-04-16,2025-01-13,37793.0,6.0,tinaknapp@example.org,9898365939,India
9960,CUST6220,John Rodriguez,male,51.0,Hyderabad,2021-03-28,2025-01-22,27102.0,10.0,laurahart@example.com,7462990833,India
10140,CUST4367,Amber Kennedy,F,61.0,Bangalore,2023-11-05,2025-01-10,40711.0,8.0,kellifox@example.com,5600790669,India

In [25]:
df[df['Customer_ID'] == "CUST2755"]

,Customer_ID,Name,Gender,Age,City,Signup_Date,Last_Purchase_Date,Purchase_Amount,Feedback_Score,Email,Phone_Number,Country
1874,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India
2032,CUST2755,Casey Campbell,male,NaN,Hyderabad,2023-12-01,2024-11-04,11778.0,3.0,joseph49@example.com,3844741384,India

In [27]:
for col in df.columns:
    if df[col].nunique() < 20:
        print(df[col].value_counts())
        print('-'*50)

Gender
f         1184
M         1171
m         1163
F         1157
MALE      1131
female    1128
male      1121
FEMALE    1119
Name: count, dtype: int64
--------------------------------------------------
City
Kolkata       820
Mumbai        812
Chennai       784
Bangalore     773
Hyderabad     770
Delhi         763
CHENNAI       404
KOLKATA       395
MUMBAI        393
hyderabad     384
bangalore     383
DELHI         378
delhi         369
BANGALORE     363
HYDERABAD     360
mumbai        352
chennai       343
kolkata       338
Name: count, dtype: int64
--------------------------------------------------
Feedback_Score
2.0     952
4.0     947
7.0     938
6.0     927
3.0     913
8.0     912
1.0     907
9.0     903
10.0    901
5.0     877
Name: count, dtype: int64
--------------------------------------------------
Country
India    7132
IND       793
india     772
InDia     771
Name: count, dtype: int64
--------------------------------------------------

## Handling Missing Values

In [30]:
df.dropna(subset=['Customer_ID'],inplace=True)
df.isnull().sum()

Customer_ID             0
Name                    0
Gender                934
Age                   859
City                  918
Signup_Date             0
Last_Purchase_Date    914
Purchase_Amount       927
Feedback_Score        905
Email                   0
Phone_Number            0
Country               664
dtype: int64

In [33]:
df['Age'].unique()

<StringArray>
[      '52.0', '51.0 years',       '62.0',       '40.0',       '41.0',
          nan,       '18.0', '43.0 years', '40.0 years',       '26.0',
 ...
        '-10', '60.0 years', '24.0 years', '26.0 years', '21.0 years',
 '64.0 years', '50.0 years', '68.0 years', '32.0 years', '56.0 years']
Length: 109, dtype: str

In [40]:
import re
def extract_age(age):
    age_num = re.findall(r'\d+',str(age))
    if len(age_num) > 0:
        return age_num[0]
    else :
        return age

df['Age'] = df['Age'].apply(lambda x : extract_age(x))

In [42]:
df['Age'].unique()

<StringArray>
[       '52',        '51',        '62',        '40',        '41',         nan,
        '18',        '43',        '26',        '32',        '22',        '59',
        '65',        '61',        '31',        '54',        '55',        '69',
        '24',        '63',        '19',        '50',        '56',        '36',
        '68',        '38',        '27',        '57',        '23',        '25',
        '66',        '28',        '30',        '46',        '48',        '20',
        '37',        '67',        '35',        '58',        '29', 'nan years',
        '39',        '49',        '47',        '42',        '44',        '64',
        '53',        '60',        '45',        '21',        '34',        '33',
       '250',         '3',        '10']
Length: 57, dtype: str

In [45]:
df[df['Age'] != 'nan years']['Age']

0        52
1        51
2        62
3        40
4        41
         ..
10194    40
10195    35
10197    25
10198    55
10199    34
Name: Age, Length: 9120, dtype: str